use super::*;

pub(super) fn candidate(id: &str, symbol: &str) -> PaperWatchCandidate {
    PaperWatchCandidate {
        paper_watch_candidate_id: id.to_owned(),
        candidate_id: format!("cand_{id}"),
        candidate_lifecycle_key: format!("cand_{id}:v1"),
        symbol_canonical: symbol.to_owned(),
        source_research_run_id: "research_run_001".to_owned(),
        source_research_packet_id: "packet_001".to_owned(),
        source_research_bias: ResearchBias::RetestBias,
        historical_survival_band: SurvivalBand::Stable,
        admission_reason_codes: vec!["retest_positive_watch_admitted".to_owned()],
        blocked_promotion_reason_codes: vec!["needs_forward_observation".to_owned()],
        replay_sample_summary: PaperWatchReplaySampleSummary {
            research_aggregate_key: "agg_001".to_owned(),
            replay_run_count: 10,
            completed_count: 5,
            positive_net_count: 3,
            non_positive_net_count: 2,
            missing_market_replay_data_count: 0,
            insufficient_evidence_count: 0,
            effective_completed_sample_weight: 5.0,
            weighted_mean_net_after_cost_bps: Some(10.0),
            weighted_profit_factor_ppm: Some(1_100_000),
        },
        expected_cost_profile: PaperExpectedCostProfile {
            fee_model_version: "fee".to_owned(),
            slippage_model_version: "slippage".to_owned(),
            estimated_cost_bps: Some(8.0),
            cost_stressed_mean_net_after_cost_bps: Some(2.0),
        },
        expected_risk_profile: PaperExpectedRiskProfile {
            survival_band: SurvivalBand::Stable,
            max_drawdown_band: "low".to_owned(),
            positive_net_count: 3,
            non_positive_net_count: 2,
        },
        target_max_holding_hours: 24,
        absolute_max_holding_hours: 72,
        force_flat_policy: "paper_watch_only_no_order_execution".to_owned(),
        paper_start_recommendation: "start_forward_paper_watch".to_owned(),
        safety: PaperWatchSafety {
            paper_only: true,
            live_enabled: false,
            order_execution_enabled: false,
            execution_approval_emitted: false,
        },
        created_at_ms: 1_000,
        schema_version: "paper_watch_candidate_v1".to_owned(),
    }
}

pub(super) fn tick(id: &str, symbol: &str, timestamp_ms: i64, mark_price: f64) -> MarketLiveTick {
    MarketLiveTick {
        schema_version: MARKET_LIVE_TICK_SCHEMA_VERSION.to_owned(),
        event_id: id.to_owned(),
        producer_run_id: "market_run_001".to_owned(),
        venue: "binance".to_owned(),
        source_role: "reference".to_owned(),
        market_type: "spot".to_owned(),
        event_type: "trade".to_owned(),
        symbol_native: format!("{symbol}USDT"),
        symbol_canonical: symbol.to_owned(),
        base_asset: symbol.to_owned(),
        quote_asset: "USDT".to_owned(),
        exchange_timestamp_ms: timestamp_ms,
        ingest_timestamp_ms: timestamp_ms + 10,
        latency_ms: 10,
        sequence_id: id.to_owned(),
        sequence_tag: "trade_id".to_owned(),
        price_source: "last_price".to_owned(),
        last_price: Some(mark_price),
        best_bid_price: None,
        best_ask_price: None,
        mark_price: Some(mark_price),
        quantity: Some(1.0),
        raw_payload_sha256: "sha256:test".to_owned(),
    }
}
