use crate::model::ReplayRun;
use std::collections::BTreeSet;

#[derive(Debug)]
pub(in crate::gate::aggregate) struct AggregateAccumulator {
    pub(in crate::gate::aggregate) research_aggregate_key: String,
    pub(in crate::gate::aggregate) research_partition_keys: BTreeSet<String>,
    pub(in crate::gate::aggregate) source_candidate_ids: BTreeSet<String>,
    pub(in crate::gate::aggregate) source_candidate_lifecycle_keys: BTreeSet<String>,
    pub(in crate::gate::aggregate) symbol_canonical: String,
    pub(in crate::gate::aggregate) hypothesis_type: String,
    pub(in crate::gate::aggregate) validation_adapter: String,
    pub(in crate::gate::aggregate) strategy_id_or_family: String,
    pub(in crate::gate::aggregate) parameter_variant_id: String,
    pub(in crate::gate::aggregate) replay_run_count: usize,
    pub(in crate::gate::aggregate) active_replay_run_count: usize,
    pub(in crate::gate::aggregate) expired_replay_run_count: usize,
    pub(in crate::gate::aggregate) completed_count: usize,
    pub(in crate::gate::aggregate) decayed_completed_count: usize,
    pub(in crate::gate::aggregate) expired_completed_count: usize,
    pub(in crate::gate::aggregate) effective_completed_sample_weight: f64,
    pub(in crate::gate::aggregate) invalid_input_count: usize,
    pub(in crate::gate::aggregate) missing_market_replay_data_count: usize,
    pub(in crate::gate::aggregate) insufficient_evidence_count: usize,
    pub(in crate::gate::aggregate) liquidity_filter_materialized_count: usize,
    pub(in crate::gate::aggregate) liquidity_filter_passed_count: usize,
    pub(in crate::gate::aggregate) liquidity_filter_failed_count: usize,
    pub(in crate::gate::aggregate) positive_net_count: usize,
    pub(in crate::gate::aggregate) non_positive_net_count: usize,
    pub(in crate::gate::aggregate) raw_returns: Vec<f64>,
    pub(in crate::gate::aggregate) btc_adjusted_returns: Vec<f64>,
    pub(in crate::gate::aggregate) net_after_costs: Vec<f64>,
    pub(in crate::gate::aggregate) cost_estimates: Vec<f64>,
    pub(in crate::gate::aggregate) gross_positive_net_bps: f64,
    pub(in crate::gate::aggregate) gross_negative_net_bps_abs: f64,
    pub(in crate::gate::aggregate) weighted_positive_net_bps: f64,
    pub(in crate::gate::aggregate) weighted_negative_net_bps_abs: f64,
    pub(in crate::gate::aggregate) weighted_positive_sample_weight: f64,
    pub(in crate::gate::aggregate) weighted_net_after_cost_sum: f64,
    pub(in crate::gate::aggregate) active_replay_windows: BTreeSet<String>,
    pub(in crate::gate::aggregate) market_regime_labels: BTreeSet<String>,
    pub(in crate::gate::aggregate) completed_samples: Vec<crate::gate::sample::CompletedSample>,
    pub(in crate::gate::aggregate) required_unseen_windows: usize,
    pub(in crate::gate::aggregate) train_validation_split_required: bool,
    pub(in crate::gate::aggregate) liquidity_filter_required: bool,
}

impl AggregateAccumulator {
    pub(in crate::gate::aggregate) fn new(run: &ReplayRun) -> Self {
        Self {
            research_aggregate_key: run.research_aggregate_key.clone(),
            research_partition_keys: BTreeSet::new(),
            source_candidate_ids: BTreeSet::new(),
            source_candidate_lifecycle_keys: BTreeSet::new(),
            symbol_canonical: run.symbol_canonical.clone(),
            hypothesis_type: run.hypothesis_type.clone(),
            validation_adapter: run.validation_adapter.clone(),
            strategy_id_or_family: run.strategy_id_or_family.clone(),
            parameter_variant_id: run.parameter_variant_id.clone(),
            replay_run_count: 0,
            active_replay_run_count: 0,
            expired_replay_run_count: 0,
            completed_count: 0,
            decayed_completed_count: 0,
            expired_completed_count: 0,
            effective_completed_sample_weight: 0.0,
            invalid_input_count: 0,
            missing_market_replay_data_count: 0,
            insufficient_evidence_count: 0,
            liquidity_filter_materialized_count: 0,
            liquidity_filter_passed_count: 0,
            liquidity_filter_failed_count: 0,
            positive_net_count: 0,
            non_positive_net_count: 0,
            raw_returns: Vec::new(),
            btc_adjusted_returns: Vec::new(),
            net_after_costs: Vec::new(),
            cost_estimates: Vec::new(),
            gross_positive_net_bps: 0.0,
            gross_negative_net_bps_abs: 0.0,
            weighted_positive_net_bps: 0.0,
            weighted_negative_net_bps_abs: 0.0,
            weighted_positive_sample_weight: 0.0,
            weighted_net_after_cost_sum: 0.0,
            active_replay_windows: BTreeSet::new(),
            market_regime_labels: BTreeSet::new(),
            completed_samples: Vec::new(),
            required_unseen_windows: 0,
            train_validation_split_required: false,
            liquidity_filter_required: false,
        }
    }
}
